app = "aa-zero-records"
primary_region = 'iad'

[build]
image = "registry.hub.docker.com/rocicorp/zero:0.22.2025070600"

[http_service]
internal_port = 4848
force_https = true
auto_stop_machines = 'off'
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"

[[vm]]
size = "performance-1x"

[mounts]
source = "sqlite_db"
destination = "/data"
initial_size = "100gb"

[env]
ZERO_REPLICA_FILE="/data/zero-records.db"
ZERO_SCHEMA_PATH="zero/schema.ts"
ZERO_LOG_LEVEL="debug"
ZERO_QUERY_HYDRATION_STATS="true"
ZERO_LOG_SLOW_HYDRATE_THRESHOLD="1"
ZERO_APP_PUBLICATIONS="zero_data"
# Set via fly secret
# ZERO_UPSTREAM_DB=""
# ZERO_AUTH_JWKS_URL=""
# ZERO_PUSH_URL=""
# ZERO_ADMIN_PASSWORD=""
