/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCartRouteImport } from './routes/_layout/cart'
import { Route as LayoutArtistRouteImport } from './routes/_layout/artist'
import { ServerRoute as ApiOpenapiDotjsonServerRouteImport } from './routes/api/openapi[.]json'
import { ServerRoute as ApiDocsServerRouteImport } from './routes/api/docs'
import { ServerRoute as ApiZeroQueryServerRouteImport } from './routes/api/zero/query'
import { ServerRoute as ApiZeroMutateServerRouteImport } from './routes/api/zero/mutate'
import { ServerRoute as ApiMutatorsSplatServerRouteImport } from './routes/api/mutators/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCartRoute = LayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutArtistRoute = LayoutArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const ApiOpenapiDotjsonServerRoute = ApiOpenapiDotjsonServerRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDocsServerRoute = ApiDocsServerRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiZeroQueryServerRoute = ApiZeroQueryServerRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiZeroMutateServerRoute = ApiZeroMutateServerRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMutatorsSplatServerRoute = ApiMutatorsSplatServerRouteImport.update({
  id: '/api/mutators/$',
  path: '/api/mutators/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/artist': typeof LayoutArtistRoute
  '/cart': typeof LayoutCartRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/artist': typeof LayoutArtistRoute
  '/cart': typeof LayoutCartRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/artist': typeof LayoutArtistRoute
  '/_layout/cart': typeof LayoutCartRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/artist' | '/cart' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/artist' | '/cart' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/artist'
    | '/_layout/cart'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/docs': typeof ApiDocsServerRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/mutators/$': typeof ApiMutatorsSplatServerRoute
  '/api/zero/mutate': typeof ApiZeroMutateServerRoute
  '/api/zero/query': typeof ApiZeroQueryServerRoute
}
export interface FileServerRoutesByTo {
  '/api/docs': typeof ApiDocsServerRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/mutators/$': typeof ApiMutatorsSplatServerRoute
  '/api/zero/mutate': typeof ApiZeroMutateServerRoute
  '/api/zero/query': typeof ApiZeroQueryServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/docs': typeof ApiDocsServerRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/mutators/$': typeof ApiMutatorsSplatServerRoute
  '/api/zero/mutate': typeof ApiZeroMutateServerRoute
  '/api/zero/query': typeof ApiZeroQueryServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/auth/$'
    | '/api/mutators/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/auth/$'
    | '/api/mutators/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
  id:
    | '__root__'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/auth/$'
    | '/api/mutators/$'
    | '/api/zero/mutate'
    | '/api/zero/query'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiDocsServerRoute: typeof ApiDocsServerRoute
  ApiOpenapiDotjsonServerRoute: typeof ApiOpenapiDotjsonServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiMutatorsSplatServerRoute: typeof ApiMutatorsSplatServerRoute
  ApiZeroMutateServerRoute: typeof ApiZeroMutateServerRoute
  ApiZeroQueryServerRoute: typeof ApiZeroQueryServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/cart': {
      id: '/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/artist': {
      id: '/_layout/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof LayoutArtistRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/mutators/$': {
      id: '/api/mutators/$'
      path: '/api/mutators/$'
      fullPath: '/api/mutators/$'
      preLoaderRoute: typeof ApiMutatorsSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutArtistRoute: typeof LayoutArtistRoute
  LayoutCartRoute: typeof LayoutCartRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutArtistRoute: LayoutArtistRoute,
  LayoutCartRoute: LayoutCartRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiDocsServerRoute: ApiDocsServerRoute,
  ApiOpenapiDotjsonServerRoute: ApiOpenapiDotjsonServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiMutatorsSplatServerRoute: ApiMutatorsSplatServerRoute,
  ApiZeroMutateServerRoute: ApiZeroMutateServerRoute,
  ApiZeroQueryServerRoute: ApiZeroQueryServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
