// @generated drizzle-zero signature:sha256:88ed21a0efdf80a77e2238d7d899258cc55f0138c26386b0b66d1566322e152c
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type {Row} from '@rocicorp/zero';
import {createBuilder} from '@rocicorp/zero';

const accountTable = {
  name: 'account',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    accountId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'account_id',
    },
    providerId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'provider_id',
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    accessToken: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'access_token',
    },
    refreshToken: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'refresh_token',
    },
    idToken: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'id_token',
    },
    accessTokenExpiresAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'access_token_expires_at',
    },
    refreshTokenExpiresAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'refresh_token_expires_at',
    },
    scope: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    password: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const;
const albumTable = {
  name: 'album',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    artistId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'artist_id',
    },
    title: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    year: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const;
const artistTable = {
  name: 'artist',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    sortName: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'sort_name',
    },
    type: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    beginDate: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'begin_date',
    },
    endDate: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'end_date',
    },
    popularity: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const;
const cartItemTable = {
  name: 'cartItem',
  columns: {
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
    albumId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'album_id',
    },
    addedAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'added_at',
    },
  },
  primaryKey: ['userId', 'albumId'],
  serverName: 'cart_item',
} as const;
const jwksTable = {
  name: 'jwks',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    publicKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'public_key',
    },
    privateKey: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'private_key',
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
  },
  primaryKey: ['id'],
} as const;
const sessionTable = {
  name: 'session',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'expires_at',
    },
    token: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
    ipAddress: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'ip_address',
    },
    userAgent: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
      serverName: 'user_agent',
    },
    userId: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
      serverName: 'user_id',
    },
  },
  primaryKey: ['id'],
} as const;
const userTable = {
  name: 'user',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: 'boolean',
      optional: true,
      customType: null as unknown as boolean,
      serverName: 'email_verified',
    },
    image: {
      type: 'string',
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const;
const verificationTable = {
  name: 'verification',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    identifier: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
      serverName: 'expires_at',
    },
    createdAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'created_at',
    },
    updatedAt: {
      type: 'number',
      optional: true,
      customType: null as unknown as number,
      serverName: 'updated_at',
    },
  },
  primaryKey: ['id'],
} as const;
const albumRelationships = {
  artist: [
    {
      sourceField: ['artistId'],
      destField: ['id'],
      destSchema: 'artist',
      cardinality: 'one',
    },
  ],
  cartItems: [
    {
      sourceField: ['id'],
      destField: ['albumId'],
      destSchema: 'cartItem',
      cardinality: 'many',
    },
  ],
} as const;
const artistRelationships = {
  albums: [
    {
      sourceField: ['id'],
      destField: ['artistId'],
      destSchema: 'album',
      cardinality: 'many',
    },
  ],
} as const;
const cartItemRelationships = {
  album: [
    {
      sourceField: ['albumId'],
      destField: ['id'],
      destSchema: 'album',
      cardinality: 'one',
    },
  ],
  user: [
    {
      sourceField: ['userId'],
      destField: ['id'],
      destSchema: 'user',
      cardinality: 'one',
    },
  ],
} as const;
const userRelationships = {
  cartItems: [
    {
      sourceField: ['id'],
      destField: ['userId'],
      destSchema: 'cartItem',
      cardinality: 'many',
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    album: albumTable,
    artist: artistTable,
    cartItem: cartItemTable,
    jwks: jwksTable,
    session: sessionTable,
    user: userTable,
    verification: verificationTable,
  },
  relationships: {
    album: albumRelationships,
    artist: artistRelationships,
    cartItem: cartItemRelationships,
    user: userRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Account = Row<(typeof schema)['tables']['account']>;
/**
 * Represents a row from the "album" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Album = Row<(typeof schema)['tables']['album']>;
/**
 * Represents a row from the "artist" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Artist = Row<(typeof schema)['tables']['artist']>;
/**
 * Represents a row from the "cartItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CartItem = Row<(typeof schema)['tables']['cartItem']>;
/**
 * Represents a row from the "jwks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Jwk = Row<(typeof schema)['tables']['jwks']>;
/**
 * Represents a row from the "session" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<(typeof schema)['tables']['session']>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)['tables']['user']>;
/**
 * Represents a row from the "verification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Verification = Row<(typeof schema)['tables']['verification']>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' {
  interface DefaultTypes {
    schema: Schema;
  }
}
